### ISSUE TITLE
Players can join even after they are banned

### ISSUE THREAD

**Issue by jaboy** [grandwazir/BanHammer#70] opened 2013-06-30 18:49 UTC
Hey

i have a problem ... players can join even though they are banned
the ban stand like this in the database

901 2013-06-19 23:12:04 Grief (Fire - Ashorts build - Survival)     0   820 2

but anyway the person is online ... doing a /bh check "playername" also shows that he is banned

There are no errors in console or anywhere else
the playername is sabercatfan97

restarting the server seems to fix it ... but it is annoying anyway

**Comment by grandwazir** [comment] 2013-06-30 19:21
What version of BanHammer are you using?

**Comment by jaboy** [comment] 2013-06-30 22:57
looking in the plugin.yml inside the plugin say version: 2.2.5

**Comment by darrenstraight** [comment] 2013-07-02 10:13
I've been having the same issues, has happened at least twice, yet a server restart normally fixes the issue, been trying to reproduce it myself but haven't been able to so far. Error message received in server log just before banned player logged in:

2013-06-22 21:19:22 [SEVERE] Could not pass event AsyncPlayerPreLoginEvent to BanHammer v2.2.5
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:459)
    at net.minecraft.server.v1_5_R3.ThreadLoginVerifier.run(ThreadLoginVerifier.java:48)
Caused by: java.lang.NullPointerException
    at name.richardson.james.bukkit.banhammer.BannedPlayerListener.isBanned(BannedPlayerListener.java:121)
    at name.richardson.james.bukkit.banhammer.BannedPlayerListener.onPlayerLogin(BannedPlayerListener.java:63)
    at sun.reflect.GeneratedMethodAccessor174.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
    ... 4 more

Also someone else reporting it here:
http://dev.bukkit.org/bukkit-plugins/banhammer/#c262

Thanks,
Darren

**Comment by jaboy** [comment] 2013-07-02 10:31
im not having the same error as darren (i dont have one)

but i noticed now, when i try to ban a player it tells me the player is already banned ... the problem is just that the ban expired "20 Aug 2012" .... and thats a really really old ban i made on him

**Comment by jaboy** [comment] 2013-07-02 18:56
i just notect that it is only temp ban that dont work as they should ... perm works just fine :/

**Comment by jaboy** [comment] 2013-07-02 21:37
now i got a error

org.apache.commons.lang.UnhandledException: Plugin BanHammer v2.2.1 generated an exception while executing task 16
    at org.bukkit.craftbukkit.v1_6_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key updater.new-version-available
    at java.util.ResourceBundle.getObject(Unknown Source)
    at java.util.ResourceBundle.getString(Unknown Source)
    at name.richardson.james.bukkit.banhammer.utilities.updater.PluginUpdater.getMessage(PluginUpdater.java:89)
    at name.richardson.james.bukkit.banhammer.utilities.updater.PluginUpdater.run(PluginUpdater.java:109)
    at org.bukkit.craftbukkit.v1_6_R1.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_6_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more

**Comment by jaboy** [comment] 2013-07-02 21:52
okey this is fixed in version 2.2.6 :+1:

**Comment by MarioG1** [comment] 2013-07-03 15:48
Where can i download 2.2.6??

**Comment by jaboy** [comment] 2013-07-03 18:16
quote from a comment grandwazir made on hes own plugin

I would like some testers to try out the new version before I release it properly. This is to avoid the problems we had last time. Everything should work. If you encounter any problems set debugging on by going to the config.yml and setting logging to "FINEST".

Please try it out at the following address. Do not run it on anything important though (if you do please do make a backup first).

http://repository.james.richardson.name/snapshots/name/richardson/james/bukkit/ban-hammer/2.2.6-SNAPSHOT/

The above website does contain software which has not been directly approved by dev.bukkit staff and as such require the following disclaimer: Development builds of this project can be acquired at the provided continuous integration server. These builds have not been approved by the BukkitDev staff. Use them at your own risk.

**Comment by ArtificialTruth** [comment] 2013-07-07 16:04
I can confirm for  2.2.5

**Comment by maroselis** [comment] 2013-08-10 22:39
Also can confirm for 2.2.5

**Comment by grandwazir** [comment] 2013-08-15 10:49
This has been confirmed as fixed by one other person in the new development version of BanHammer available [here](http://repository.james.richardson.name/snapshots/name/richardson/james/bukkit/ban-hammer/2.3.0-SNAPSHOT/). 

If for whatever reason it occurs again, put the plugin into debug mode (by setting logging to ALL) and give me any relevant information. If you banned anyone when running 2.2.2 - 2.2.4 you may need to ban them again. All future bans will function properly. 

I am going to close this issue now. Reopen it if it reoccurs on the new development version.

**Closed as completed by grandwazir** 2013-08-15 10:49 UTC
Labels: Bug
