### ISSUE TITLE
Purge + Announce Issue

### ISSUE THREAD

**Issue by xDeeKay** [grandwazir/BanHammer#41] opened 2012-12-13 16:23 UTC
I can't seem to purge any players bans. I get the message 'PURGECOMMAND.PURGED' and the bans of a player still exist after running the command.

Also, players are receiving notifications when people are banned or kicked without the banhammer.notify permission. The permission isn't in any user or group permission list.

**Comment by grandwazir** [comment] 2012-12-13 18:21
Thanks for reporting this issue. 
1. This is a bug and will be fixed in the next version.
2. The second issue is that way by design. 

`banhammer.notify` is given to everyone by default. If you do not wish everyone to get the notifications you will need to set it to false for those players using your favorite permission manager or through bukkit.yml.

**Comment by grandwazir** [comment] 2012-12-13 23:25
Fixed another issue with this command and not returning helpful error messages.

**Closed as completed by grandwazir** 2012-12-13 23:25 UTC
Labels: Bug, Support
