### ISSUE TITLE
Multiple of the Same person in database

### ISSUE THREAD

**Issue by rmb938** [grandwazir/BanHammer#40] opened 2012-11-15 02:46 UTC
Some how two of the same person is appearing in the database and you are unable to ban them because of that. I am using MySQL. I don't know what is causing it.

**Comment by grandwazir** [comment] 2012-11-18 15:30
This is a duplicate of #34. It is a rare situation that BanHammer can get itself into. If you follow the instructions in that thread you will be able to solve the problem. 

If you are unable to do that you can email me a copy of your database and I will fix it for you.

**Comment by rmb938** [comment] 2012-11-20 15:39
Yes that is what I have been doing but if you have thousands of different plays play on your server every week and of course a lot of bans this because a very common issue. Can't you just add something that keeps a list of who is in the database and who isn't so this bug doesn't happen. Something like this should be a very easy fix.

**Comment by grandwazir** [comment] 2012-12-13 18:13
The bug was easy to fix and has been fixed. It was introduced with a development build that was released briefly a while ago. The problem does not occur anymore. 

What is harder to do is to create a tool to automatically fix these errors when they occur. The amount of people who have had this problem means that has not been necessary.

That said I am obviously concerned if you are still having issues and my earlier offer stands; you can email me your database and I will look at it if you are still having issues.

**Closed as completed** 2012-12-30 01:27 UTC
Labels: Support
