### ISSUE TITLE
Problem with ban/pardon permissions

### ISSUE THREAD

**Issue by MarioG1** [grandwazir/BanHammer#67] opened 2013-06-24 06:44 UTC
My mods have:

banhammer.ban.long
banhammer.pardon.own

but if i try to execute /ban name t:1d reason for example, i always get the message 
"You are not allowed to do this".

You can only ban/paron people if you have

banhammer.ban
banhammer.pardon

Plugin versions:

Bukkit: 1.5.2 R 1.0
Banhammer: 2.2.6-20130621.234610-1
Permissions: PermissionsEX 1.19.6

Server log without banhammer debugging but with PEX in debug mode (Idk how to turn it on because there is no config option) :

http://pastebin.com/FJJEfvJf

**Comment by grandwazir** [comment] 2013-06-24 09:56
I can confirm the issue with the pardon command. Didn't know about the other one. 

I found the pardon bug myself this weekend. The problem is the permission that is actually checked is `banhammer.audit.others` instead of `banhammer.pardon.others`. It has already been fixed.

I'll look into the BanCommand playing up again as well.

**Comment by grandwazir** [comment] 2014-04-17 19:12
This is confirmed as fixed in the latest build.

**Closed as completed by grandwazir** 2014-04-17 19:12 UTC
Labels: Bug
